name: Rust-Python Hybrid Template
description: "A template for creating Python packages with Rust extensions using PyO3 and Maturin"
tags:
  - python
  - rust
  - pyo3
  - maturin
  - hybrid
  - template
  - nix
  - development
include:
  - "*"
exclude:
  - ".template-initialized"
